name: learn-github-actions
on: [push]
jobs:
  on-push-get-changed-file:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
      with: 
        fetch-depth: 2
    - name: get changed file
      run: git diff --shortstat HEAD^ HEAD | cut -c 5-100 | grep -o -E "[0-9]+"
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
